"""Asset management utilities for jinja-ui-kit."""

from importlib.resources import files


def get_css_path() -> str:
    """Get the path to the jinja-ui-kit CSS file.

    Returns:
        str: Absolute path to the jinja-ui-kit.min.css file

    Raises:
        FileNotFoundError: If the CSS file is not found
    """
    css_file = files("jinja_ui_kit") / "dist" / "jinja-ui-kit.min.css"
    return str(css_file)


def get_template_path() -> str:
    """Get the path to the jinja-ui-kit templates directory.

    Returns:
        str: Absolute path to the templates directory
    """
    return str(files("jinja_ui_kit") / "templates")


def write_tailwind_content(output_path: str = "jinja_ui_kit_tailwind.js") -> None:
    """Write a JS file exporting the template content glob for use in tailwind.config.js.

    The output file contains a machine-specific absolute path — add it to .gitignore
    and regenerate it as part of your build step.

    Usage in tailwind.config.js:
        const { content: kitContent } = require('./jinja_ui_kit_tailwind.js');
        module.exports = {
            content: ['./src/templates/**/*.html', ...kitContent],
        };
    """
    template_glob = get_template_path() + "/**/*.html"
    content = (
        "// Auto-generated by jinja-ui-kit. Add to .gitignore.\n"
        f'module.exports = {{ content: ["{template_glob}"] }};\n'
    )
    with open(output_path, "w") as f:
        f.write(content)
